# Generated by Django 4.0.4 on 2022-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('isActive', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
