# Generated by Django 4.0.4 on 2022-05-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthController', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
